### ISSUE TITLE
register error after creating new database 

### ISSUE THREAD

**Issue by sahilvadia7** [ChiragAgg5k/bu-news-android#2]
can you address me where change API KEY and database object. I cant see anywhere please help me out i am curious about app layouts, fragment and flow you do very good work i am trying to learn !

**Comment by ChiragAgg5k** [comment]
Hey there. You only need to add one file, i.e the `google-services.json` file, which you will get after creating a new firebase project. You need to add the file in the `app` directory.

<img width="254" alt="Screenshot 2023-12-16 at 11 04 17 AM" src="https://github.com/ChiragAgg5k/bu-news-android/assets/110609663/e5f15e72-931e-4391-9ef1-9efaa535b3f8">

For more info - https://www.google.com/search?q=firebase+google+services+json&oq=firebase+google+services+j&sourceid=chrome&ie=UTF-8

**Comment by sahilvadia7** [comment]
thank you !
